##
## EPITECH PROJECT, 2020
## Dashboard
## File description:
## docker-compose.yml
##

version: "3"

services:
    server:
        image: dashboard:latest
        restart: on-failure
        networks:
            - dashboard-tier
        ports:
            - "8080:8080"
        environment:
            PORT: 8080

networks:
    dashboard-tier:
